### ISSUE TITLE
Комментарии - зло

### ISSUE THREAD

**Issue by Red-Cat-Fat** [bbno-c/Lesson-2.-Clicker#4]
Зачем тебе закомиченный метод? Git тебе на что?
https://github.com/bbno-c/Lesson-2.-Clicker/blob/4ce2cb06981105da4595709edf05ac7614cbe280/Assets/Scripts/Cubes.cs#L35-L44

**Comment by bbno-c** [comment]
Убрал комментарий
https://github.com/bbno-c/Lesson-2.-Clicker/commit/1c53b1979d050aa0454d81d17de3c69b8919cf6c
