### ISSUE TITLE
Инкапсуляция

### ISSUE THREAD

**Issue by Red-Cat-Fat** [bbno-c/Lesson-2.-Clicker#6]
А действительно это нужно было сделать публичной переменной? Почему не [SerializeField] private? И зачем он тебе вообще, если у тебя есть спавнер?
https://github.com/bbno-c/Lesson-2.-Clicker/blob/4ce2cb06981105da4595709edf05ac7614cbe280/Assets/Scripts/MouseCoordinates.cs#L7

**Comment by Red-Cat-Fat** [comment]
Тут та же история. Только зачем тебе [SerializeField] к public переменной?
https://github.com/bbno-c/Lesson-2.-Clicker/blob/4ce2cb06981105da4595709edf05ac7614cbe280/Assets/Scripts/spawner.cs#L8-L16

**Comment by bbno-c** [comment]
Cube - это префаб куба, который я собираюсь спавнить. Ели я делаю это поле приватным, мне среда выдаёт предупреждение:

> Assets\Scripts\Spawner.cs(8,42): warning CS0649: Field 'Spawner.CubePrefab' is never assigned to, and will always have its default value null

**Comment by bbno-c** [comment]
Cube - это префаб. Как задать, что спавнер будет спавнить без такого поля?

**Comment by Red-Cat-Fat** [comment]
Почитай что такое SerializeField

**Comment by bbno-c** [comment]
https://github.com/bbno-c/Lesson-2.-Clicker/commit/1c53b1979d050aa0454d81d17de3c69b8919cf6c
