### ISSUE TITLE
А редактор на что?

### ISSUE THREAD

**Issue by Red-Cat-Fat** [bbno-c/Lesson-2.-Clicker#7]
Ты же можешь в редакторе Unity задать все переменные, причём даже менять их динамически
https://github.com/bbno-c/Lesson-2.-Clicker/blob/4ce2cb06981105da4595709edf05ac7614cbe280/Assets/Scripts/spawner.cs#L20

**Comment by bbno-c** [comment]
https://github.com/bbno-c/Lesson-2.-Clicker/commit/c34d7bdd5d522838226d9e156c7d7532459a0111
